apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd-autopilot
    app.kubernetes.io/name: kiali
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  source:
    repoURL: https://kiali.org/helm-charts
    chart: kiali-server
    targetRevision: 2.3.0
    helm:
      parameters:
        - name: auth.strategy
          value: "anonymous"
        - name: deployment.image_version
          value: "v2.3.0"
        - name: external_services.custom_dashboards.enabled
          value: "true"
        - name: external_services.prometheus.url
          value: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"
        - name: external_services.grafana.enabled
          value: "true"
        - name: external_services.grafana.url
          value: "http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local:80"
        - name: external_services.grafana.in_cluster_url
          value: "http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local:80"
        - name: external_services.grafana.auth.username
          value: "admin"
        - name: external_services.grafana.auth.password
          value: "admin123"
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
