apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd-autopilot
    app.kubernetes.io/name: kiali
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  source:
    repoURL: https://kiali.org/helm-charts
    chart: kiali-server
    targetRevision: 2.3.0
    helm:
      values: |
        auth:
          strategy: "anonymous"
        deployment:
          image_version: "v2.3.0"
        external_services:
          custom_dashboards:
            enabled: true
          prometheus:
            url: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"
          grafana:
            enabled: true
            url: "http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local:80"
            in_cluster_url: "http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local:80"
            auth:
              username: "admin"
              password: "admin123"
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
