apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: technovise-wildcard-cert
  namespace: istio-ingress
spec:
  secretName: technovise-wildcard-tls
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  commonName: "*.technovise.local"
  dnsNames:
  - "*.technovise.local"
  - "technovise.local"
  privateKey:
    algorithm: RSA
    size: 2048
