apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openvino
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd-autopilot
    app.kubernetes.io/name: openvino
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  source:
    repoURL: https://github.com/carthyr/gitops
    targetRevision: main
    path: apps/openvino/manifests
  
  destination:
    server: https://kubernetes.default.svc
    namespace: openvino
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
