apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-toolkit-resourcesync
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd-autopilot
    app.kubernetes.io/name: devops-toolkit-resourcesync
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  source:
    repoURL: https://github.com/carthyr/gitops.git
    path: apps/devops-toolkit-controller/manifests
    targetRevision: main
  
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-toolkit
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
